### ISSUE TITLE
图片恢复乱序

### ISSUE THREAD

**Issue by lxw9518** [Sexypanda8888/18comic-#1]
我有个问题请教:你说的那个函数我也看到了，分成10分，，但是有些图片不是10等分，，，，放缩了？？

**Comment by Sexypanda8888** [comment]
留个例子呗
我是直接照着JS抄到py上的呀，应该没问题。

**Comment by Sexypanda8888** [comment]
对了，我后来还发现了有的图片没有加密，是和html页面一个aid变量的大小有关系，不知道是不是因为这个。
我记得那个变量要和一个写死的变量，2开头的数字进行比较，在主页和aid是写在一起的，你可以看看。如果aid比较小那么就不加密。

我这接口写得很随便，一方面是没想到有人会用到，同时这也只是一个canvas加密的学习罢了。

**Comment by lxw9518** [comment]
原站固定10分的应该是每本书的首页展示的那几张图片，，但是你点开每一章，，会发现每章图片大部分都是按照2，6，10，20分等错位的。。没找到他是怎么确定每张图片要分割几次还原的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sexypanda8888/18comic-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 凌晨1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sexypanda8888/18comic-] 图片恢复乱序 (#1)





 
留个例子呗
 我是直接照着JS抄到py上的呀，应该没问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sexypanda8888** [comment]
那很可能是升级了，我之前看到十份是写死的
我有时间看看，今晚应该可以，你也留一下对应的链接吧
这个网站加密除了canvas也没别的了，要我说分成几份很可能就直接就放到html上了

**Comment by 1126107509** [comment]
https://18comic.org/

随便一个韩国的漫画，，你F12看一下图片连接，，都是不同的分割，，10这个固定的分割只出现在每一本书里面展示的几张图片，，你点击每一章节看的话，，分割数量不固定，，就2，6，10，20或许还有其他的分割，，我没找到动态生成的canvs代码，，也不知道他怎么动态判断一个图片几次能还原原图


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sexypanda8888/18comic-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sexypanda8888/18comic-] 图片恢复乱序 (#1)





 
那很可能是升级了
 我有时间看看，今晚应该可以，你也留一下对应的链接吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sexypanda8888** [comment]
我没找到，你发一个有不同分割方式的链接
好吧看到了，应该是比较新的漫画才会有的

**Comment by 1126107509** [comment]
https://cdn-msp.18comic.vip/media/photos/271433/00001.jpg?v=1628501153
你随便找一个3d漫画，，F12查看一下每一张的图片，，你就能看到啊https://18comic.vip/photo/269234




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sexypanda8888/18comic-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上7:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sexypanda8888/18comic-] 图片恢复乱序 (#1)





 
我没找到，你发一个有不同分割方式的链接
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sexypanda8888** [comment]
刚写好，等我发上来
话说你要拿这个来做什么啊
还有为什么你能给我发邮件我找不到地方呀

**Comment by Sexypanda8888** [comment]
还有啊，你是怎么找到这个工程的，我觉得是不太可能会被看到的

**Comment by lxw9518** [comment]
没有找到章节图片生成canvs的js代码，有点坑，所以没法判断生成canvs时需要拼接几次。。反正肯定是在一个js文件里。滚动事件肯定会触发生成canvs标签。。但是就是没找到


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sexypanda8888/18comic-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 凌晨0:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sexypanda8888/18comic-] 图片恢复乱序 (#1)





 
还有啊，你是怎么找到这个工程的，我觉得是不太可能会被看到的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sexypanda8888** [comment]
你要和我讨论的话，直接加Q1719705266
